src/console/urls.py
"""Routing http request by uri"""
from django.conf.urls import url
from django.conf.urls import include
from . import views, firmware, tab
from . import api, dt

urlpatterns = [

    # pages
    url(r'^$', views.index, name='index'),
    url(r'^utilities', views.utilities, name='utilities'),
    url(r'^resources', views.resources, name='resources'),

    url(r'^datatables', views.resources_new, name='datatables'),
    url(r'^users', views.users, name='users'),
    url(r'^settings', views.settings, name='settings'),
    url(r'^status', views.status, name='status'),
    url(r'^livelog', views.livelog, name='livelog'),
   
    #forms    
    url(r'^en', views.index_en, name='en'),
    url(r'^form_save', views.form_save, name='form_save'),    
    url(r'^signup', views.signup, name='signup'),
    url(r'^gateway_modal', views.gateway_modal, name='gateway_modal'),        
    url(r'^registration', views.register, name='register'),
    url(r'^registration/complete/$', views.registration_complete, name='registration_complete'),
    url('^', include('django.contrib.auth.urls')),

    # api calls
    url(r'^assign_gateway', api.assign_gateway, name='assign_gateway'),
    url(r'^get_messages_for_console', api.get_messages_for_console, name='get_messages'),
    url(r'^get_chart_data', api.get_chart_data, name='get_chart_data'),  
    url(r'^get_node_data', api.get_node_data, name='get_node_data'),  
    url(r'^get_files_data', api.get_files_data, name='get_files_data'),
    url(r'^get_nodes_sensors', api.get_nodes_sensors, name='get_nodes_sensors'),
    url(r'^edit_node', api.edit_node, name='edit_node'),
    url(r'^delete_node', api.delete_node, name='delete_node'),

    url(r'^send_mqtt', api.send_mqtt_message, name='send_mqtt_message'),

    # # file api 
    # url(r'^upload', api.upload, name='upload'),
    # url(r'^delete', api.delete, name='delete'),

    # datatables 
    url(r'^get_gateway_table', dt.get_gateway_table, name='get_gateway_table'),
    url(r'^get_node_table', dt.get_node_table, name='get_node_table'),
    url(r'^get_sensor_table', dt.get_sensor_table, name='get_sensor_table'),  

    # # firmware call

    url(r'^get_tab_content', tab.tab_dispatcher, name='tab_dispatcher'),  

    url(r'^new_tab', views.new_tab, name='new_tab'),  
    
    # url(r'^smartconfig.bin', firmware.firmware_handler, name='firmware'),
    # url(r'^smartconfig.spiffs.bin', firmware.firmware_handler, name='firmware'),
    # url(r'^firmware.bin', firmware.firmware_handler, name='firmware'),
    # url(r'^update', firmware.firmware_handler, name='firmware'),
    # url(r'^testing', firmware.testing, name='testing'),
]

src/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import console

from console import firmware
handler404 = 'console.views.not_found'
handler500 = 'console.views.internal_error'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^console/', include('console.urls')),
    url(r'^firmware/', include('console.routes')),
    url(r'^update/', firmware.update),
    url(r'^testing/', firmware.testing),
]

src/console/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import F
import datetime
import pytz
import logging
import os

from . import choices

log = logging.getLogger('fox')


class Client(models.Model):
    # Meta data
    reg_date = models.DateTimeField(auto_now_add=True, blank=False, null=False)

    # Regular credentials
    name = models.CharField(max_length=100, blank=False, null=False)
    email = models.CharField(max_length=100, blank=False, null=False)
    phones = models.CharField(max_length=100, blank=False, null=False)

    # region / time zone/location
    locale = models.CharField(max_length=200, blank=False, null=False)
    city = models.ForeignKey('City',blank=True,null=True)
    # currect status C/O
    status = models.CharField(max_length=50, blank=False, null=False)    

    def __str__(self):
        return self.name


class ClientMessage(models.Model):
    text = models.CharField(max_length=200, blank=False, null=False)
    channel = models.CharField(max_length=10, blank=False, null=False)


class ClientMessageQueue(models.Model):
    create_date = models.DateTimeField(auto_now_add=True, blank=False, null=False)
    message = models.ForeignKey('ClientMessage', on_delete=models.CASCADE, blank=False, null=False)
    client = models.ForeignKey('Client', on_delete=models.CASCADE, blank=False, null=False)
    status = models.IntegerField(default=0)
    delivery_date = models.DateTimeField(auto_now_add=True, blank=False, null=False)


class Connection(models.Model):
    # заполняется при регистрации нового шлюза на основании ID устройства
    name = models.CharField(max_length=50, blank=False, null=False)

    # задержка при отправки пакетов на устройства  Milliseconds
    delay = models.IntegerField(default=0)

    # наш тип коннектора
    network_type =models.CharField(max_length=50, blank=False, null=False)

    # qos
    qos = models.IntegerField(default=0)

    # автоматически их шаблона на сервере
    broker_host = models.CharField(max_length=50, blank=False, null=False)

    # формируется автоматически на основании ID устройства и добавление на сервере MQTT)
    client_id = models.ForeignKey('Client', blank=True, null=True)

    # формируется автоматически на основании “gateway”+ ID устройства + "-in"
    topic_publish = models.CharField(max_length=50, blank=False, null=False)

    # формируется автоматически на основании “gateway”+ ID устройства + "-out"
    topic_subscribe = models.CharField(max_length=50, blank=False, null=False)

    #  формируется автоматически на основании емейла и добавление на сервере MQTT
    user_login = models.CharField(max_length=50, blank=False, null=False)
    password  = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.name


class Gateway(models.Model):
    reg_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    name = models.CharField(max_length=80, blank=True, null=True)
    status_broker = models.CharField(max_length=50, blank=True, null=True)
    status = models.CharField(default='New',max_length=20, blank=True, null=True)
    mobile = models.CharField(max_length=50, blank=True, null=True)
    web	= models.CharField(max_length=50, blank=True, null=True)
    uid_gateway = models.CharField(max_length=50, blank=True, null=True)
    connection = models.ForeignKey('Connection', blank=True, null=True)
    status_seen	= models.CharField(max_length=50, blank=True, null=True)
    seen_message = models.CharField(max_length=50, blank=True, null=True)
    # Nodes/Sensors
    nodes_sensors = models.CharField(max_length=50, blank=True, null=True)
    topology = models.CharField(max_length=50, blank=True, null=True)
    client = models.ForeignKey('Client',blank=True,null=True)
    inclusion_mode = models.IntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return self.name

    def attrs(self):
        for attr, value in self.__dict__.iteritems():
            yield attr, value


class Sensor(models.Model):
    reg_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    node = models.ForeignKey('Node',blank=True,null=True)
    child_sensor_id = models.IntegerField(blank=True,null=True)
    name = models.CharField(max_length=50, blank=False, null=False)
    node_type = models.CharField(max_length=50, blank=False, null=False)    
    status_seen = models.CharField(max_length=20, blank=False, null=False)
    first_reg_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)

    def __str__(self):
        return self.name


class SensorActualData(models.Model):
    sensor = models.ForeignKey(Sensor,blank=True,null=True,on_delete=models.CASCADE)   
    receive_date = models.DateTimeField(default=timezone.now)
    variable_type = models.CharField(max_length=30, blank=False, null=False)
    value = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.variable_type + ':' + self. value

class SensorData(models.Model):
    sensor = models.ForeignKey('Sensor',blank=True,null=True, )    
    receive_date = models.DateTimeField(default=timezone.now)
    variable_type = models.CharField(max_length=30, blank=False, null=False)
    value = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.variable_type + ':' + self. value




class Node(models.Model):
    reg_date = models.DateTimeField(auto_now_add=True)
    status  = models.CharField(default='New',max_length=20, blank=False, null=False)
    public_id = models.IntegerField(blank=True,null=True)
    eui = models.CharField(max_length=50, blank=False, null=False)
    parent = models.CharField(max_length=20, blank=False, null=False)    
    send_status = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=False, null=False)
    rssi = models.FloatField(default=0.0)
    bat_level = models.FloatField(default=0.0)
    node_type = models.CharField(max_length=50, blank=False, null=False)
    protocol = models.CharField(max_length=50, blank=False, null=False)
    firmware_min = models.CharField(max_length=50, blank=False, null=False)
    firmware_maj = models.CharField(max_length=50, blank=False, null=False)
    library	 = models.CharField(max_length=50, blank=False, null=False)
    status_seen  = models.CharField(max_length=50, blank=False, null=False)
    sensors	 = models.CharField(max_length=50, blank=False, null=False)
    topology = models.CharField(max_length=50, blank=False, null=False)
    gateway = models.ForeignKey('gateway',blank=True,null=True)

    def __str__(self):
        res = self.eui if len(self.name)==0 else self.name
        return res


class NodeBatteryUsage(models.Model):
    timestamp = models.DateTimeField(default=timezone.now)
    node = models.ForeignKey('node',blank=True,null=True)
    level = models.CharField(max_length=50, blank=True, null=True)


    def __str__(self):
        return str(self.node) + ':' + self.level

class RawMessage(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    ch =  models.CharField(max_length=2000, blank=True, null=True)
    method =  models.CharField(max_length=2000, blank=True, null=True)
    properties =  models.CharField(max_length=2000, blank=True, null=True)
    body =  models.CharField(max_length=200, blank=True, null=True)


    def __str__(self):
        return self.body


class MQTTMessage(models.Model):
    """Model for parsed messages from MQTT broker"""

    timestamp = models.DateTimeField(auto_now_add=True)
    consumer_tag = models.CharField(max_length=200, blank=True, null=True)
    delivery_tag = models.CharField(max_length=200, blank=True, null=True)
    exchange = models.CharField(max_length=200, blank=True, null=True)
    redelivered = models.BooleanField(default=False)
    uri = models.CharField(max_length=200, blank=True, null=True)
    cluster_name = models.CharField(max_length=20, blank=True, null=True)
    routing_key = models.CharField(max_length=50, blank=True, null=True)
    payload = models.CharField(max_length=100, blank=True, null=True)
    gateway = models.CharField(max_length=100, blank=True, null=True)
    direction = models.CharField(max_length=3)
    node_id = models.IntegerField()
    child_sensor_id = models.IntegerField(default=0)
    command = models.IntegerField()
    ack = models.IntegerField()
    type = models.IntegerField()
    qos = models.IntegerField(default=0)
    dup = models.BooleanField(default=False)

    def __str__(self):
        return self.timestamp.strftime("%Y-%m-%d %H:%M:%S") + " " + self.routing_key  + ": " + self.payload


class AppSettings(models.Model):    
    name = models.CharField(max_length=100, blank=True, null=True)
    rus_name = models.CharField(max_length=100, blank=True, null=True)
    value = models.CharField(max_length=100, blank=True, null=True)


class HeartbeatTimer(models.Model):
    object_type = models.CharField(max_length=30, blank=True, null=True)
    last_check_date = models.DateTimeField(blank=True,null=True)    
    


class City(models.Model):    
    name = models.CharField(max_length=100, blank=True, null=True)
    short_name = models.CharField(max_length=10, blank=True, null=True)
    rus_name = models.CharField(max_length=100, blank=True, null=True)
    timezone = models.CharField(max_length=50, blank=True, null=True)
    latitude = models.FloatField(blank=True,null=True)
    longitude = models.FloatField(blank=True,null=True)           
    population = models.IntegerField(default=0,null=True) 
    
    
    def __str__(self):        
        try:
            user_timezone = pytz.timezone(self.timezone)
            fmt = '%z'        
            loc_dt = int(user_timezone.localize(datetime.datetime.now()).strftime(fmt)[1:3])

src/console/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models
from pytz import all_timezones as all_tz


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class ConnectionForm(forms.ModelForm):


    name = forms.TextInput(attrs={'class':'form-control'})

    class Meta:
        model = models.Connection
        exclude = ('id',)
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'network_type': forms.TextInput(attrs={'class':'form-control'}),
            'delay': forms.TextInput(attrs={'class':'form-control'}),
            'qos': forms.TextInput(attrs={'class':'form-control'}),
            'broker_host': forms.TextInput(attrs={'class':'form-control'}),
            'client_id': forms.TextInput(attrs={'class':'form-control'}),
            'topic_publish': forms.TextInput(attrs={'class':'form-control'}),
            'topic_subscribe': forms.TextInput(attrs={'class':'form-control'}),
            'user_login': forms.TextInput(attrs={'class':'form-control'}),
            'password': forms.PasswordInput(attrs={'class':'form-control'})
        }


class AppSettingsFormTZ(forms.ModelForm):

    class Meta:

        model = models.AppSettings
        exclude = ('id',)
        tz = [(t,t) for t in all_tz]
        widgets = {
            # 'name': forms.TextInput(attrs={'class':'form-control'}),
            # 'rus_name': forms.TextInput(attrs={'class':'form-control'}),
            'value': forms.Select(choices=tz,attrs={'class':'form-control'})
        }

class AppSettingsForm(forms.ModelForm):

    class Meta:

        model = models.AppSettings
        exclude = ('id',)
        # labels = {
        #     'name': _('Writer'),
        # }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            # 'rus_name': forms.TextInput(attrs={'class':'form-control'}),
            'value': forms.TextInput(attrs={'class':'form-control'})
        }



class DocumentForm(forms.ModelForm):
    class Meta:
        model = models.Firmware
        fields = ('name', )

src/console/routes.py
"""Routing http request by uri"""
from django.conf.urls import url
from django.conf.urls import include
from . import api,firmware

urlpatterns = [
    # firmware call
    url(r'^smartconfig.bin', firmware.firmware_handler, name='firmware'),
    url(r'^smartconfig.spiffs.bin', firmware.firmware_handler, name='firmware'),
    url(r'^firmware.bin', firmware.firmware_handler, name='firmware'),
    url(r'^update', firmware.firmware_handler, name='firmware'),
    url(r'^testing', firmware.testing, name='testing'),

    #file api 
    url(r'^upload', api.upload, name='upload'),
    url(r'^delete', api.delete, name='delete'),
]

src/console/templates/console/tabs/resources.html
<div class="tabs-container">
    <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#gateways" aria-expanded="false">Gateways</a></li>
            <li class=""><a data-toggle="tab" href="#nodes" aria-expanded="false">Nodes</a></li>
            <li class=""><a data-toggle="tab" href="#sensors" aria-expanded="false">Sensors</a></li>
    </ul>
            <div class="tab-content">               
                <div id="gateways" class="tab-pane active">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="ibox float-e-margins">
                                    <div class="ibox-content">                                        
                                        <div class="table-responsive">
                                                        <table class="table table-striped" id="GatewayTable">
                                                        </table>

                                        </div>
                                    </div>
                                </div>
                                </div>
                            </div>                                
                        </div>
                </div>
                <div id="nodes" class="tab-pane">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="ibox float-e-margins">
                                        <div class="ibox-content">                                        
                                            <div class="table-responsive">

                                                    <table class="table table-striped" id="NodeTable">
                                                        </table>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>                                
                            </div>
                    </div>
                    <div id="sensors" class="tab-pane">
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="ibox float-e-margins">
                                            <div class="ibox-content">                                        
                                                <div class="table-responsive">
                                   
                                                        <table class="table table-striped" id="SensorTable">
                                                            </table>
                                                </div>
                                            </div>
                                        </div>
                                        </div>
                                    </div>                                
                                </div>
                        </div>       
            </div>         
</div>

src/console/templates/console/tabs/settings.html
{% load tags %}

<div class="tabs-container">
     <ul class="nav nav-tabs">
         <li class="active"><a data-toggle="tab" href="#System" aria-expanded="false">System</a></li>
         <li class=""><a data-toggle="tab" href="#Notifications" aria-expanded="false">Notifications</a></li>
         <li class=""><a data-toggle="tab" href="#Metrics" aria-expanded="false">Metrics</a></li>
         <li class=""><a data-toggle="tab" href="#mqtt" aria-expanded="false"> MQTT Connectors</a></li>
         <li class=""><a data-toggle="tab" href="#ms" aria-expanded="false">Mobile server</a></li>
         <li class=""><a data-toggle="tab" href="#vm" aria-expanded="false">Variables mapper</a></li>
         <li class=""><a data-toggle="tab" href="#user" aria-expanded="false">Users and Roles</a></li>
         <li class=""><a data-toggle="tab" href="#Backup" aria-expanded="false">Backup</a></li>
     </ul>
    <div class="tab-content">
      <div id="mqtt" class="tab-pane">
          <div class="panel-body">
              <form class="m-t" action="/console/settings" method="post">
                  {% csrf_token %}
                  {% if conn_form.errors %}
                            <p style="color:red;">{{ conn_form.errors}}</p>
                  {% endif %}
                    <div class="row">
                      <div class="form-group col-md-6">
                          {{ conn_form.name|add_classes }}
                      </div>
                      <div class="form-group col-md-6">
                          {{ conn_form.delay|add_classes }}
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                          {{ conn_form.network_type|add_classes }}
                      </div>
                      <div class="form-group col-md-6">
                          {{ conn_form.qos|add_classes }}
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                          {{ conn_form.broker_host|add_classes }}
                      </div>
                      <div class="form-group col-md-6">
                          {{ conn_form.client_id|add_classes }}
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                          {{ conn_form.topic_publish|add_classes }}
                      </div>
                      <div class="form-group col-md-6">
                          {{ conn_form.topic_subscribe|add_classes }}
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-6">
                          {{ conn_form.user_login|add_classes }}
                      </div>
                      <div class="form-group col-md-6">
                          {{ conn_form.password|add_classes }}
                      </div>
                    </div>
                  <button type="submit" class="btn btn-primary m-b">Сохранить</button>
              </form>
          </div>
      </div>
        <div id="user" class="tab-pane">
            <div class="panel-body">
                <p>
                  -	Enabled<br>
                  -	Username<br>
                  -	Full name<br>
                  -	Email
                </p>
            </div>
        </div>
        <div id="vm" class="tab-pane">
                        <div class="panel-body">
                            <p>
                              -	Sensors type (Temperature/Humidity/Voltage)<br>
                              -	Variable types (Temperature/Level/Forecast)<br>
                              -	Metric type (None/Double/Binary)<br>
                              -	Unit (Температура/Влажность/Напряжение/Мощность)<br>
                              -	Unit sign (%/Ватт/км/ч)<br>
                              -	Graph settings
                            </p>
                        </div>
                    </div>
        <div id="System" class="tab-pane active">
          <div class="panel-body">
              <!--p>
                -	Интервал проверки доступности узлов -29 Минут<br>
                -	Интервал поиска узлов -45 Минут<br>
                -	Уровень логов Trace/Notice/Info/Warning/Error<br>
                -	Продолжительность хранения журналов ресурсов -60 минут<br>
                -	Автоматическая регистрация Узлов Включено/Отключено<br>
                -	Максимальное кол-во полей в таблицах  40 шт.<br>
                -	Язык интерфейса Русский/Английский<br>
                -	Формат времени 12/24 часа<br>
                -	Сообщение при входе<br>
              </p-->
              <form method="POST" action="{% url 'settings' %}">
              {% for i in settings_form%}              
              {% if i.name.value == 'timezone_for_console' %}
                    <div class="row">
                        <div class="form-group col-md-6">                              
                        <label class="control-label" for="id_name">{{i.rus_name.value}}:</label>                                      
                            <select name="timezone_for_console" class="form-control" maxlength="100" id="id_value">
                                <option value="{{ i.value.value }}">{{ i.value.value }}</option> 
                                {% for t in tz%}
                                <option value="{{ t }}">{{ t }}</option>  
                                {% endfor %}
                            </select>
                        </div>
                    </div>
              {% else %}  
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" for="id_name">{{i.rus_name.value}}:</label>                    
                        <input type="text" name="{{i.name.value}}" value="{{i.value.value}}" class="form-control" maxlength="100">
                    </div>
                </div>
              {% endif %}

              {% endfor %}              
              <button type="submit" class="btn btn-primary m-b">Сохранить</button>
            </form>
          </div>
      </div>
        </div>
  </div>
</div>

src/console/templates/console/tabs/status.html
<div class="tabs-container">
     <ul class="nav nav-tabs">
         <li class=""><a data-toggle="tab" href="#info" aria-expanded="true"> Info </a></li>
         <li class="active"><a data-toggle="tab" href="#Firmwares" aria-expanded="false">System status</a></li>
         <li class=""><a data-toggle="tab" href="#servers" aria-expanded="false">Logs</a></li>
         <li class=""><a data-toggle="tab" href="#servers" aria-expanded="false">About</a></li>
     </ul>
    <div class="tab-content">
        <div id="info" class="tab-pane">
                        <div class="panel-body">
                            <strong>some status information</strong>
                            <p>some info about our system</p>
                        </div>
                    </div>
        <div id="Firmwares" class="tab-pane">
                        <div class="panel-body">
                            <strong>some system information</strong>
                            <p>some info about Firmwares</p>
                        </div>
                    </div>
        <div id="servers" class="tab-pane active">
          <div class="panel-body">
              <strong>node #1</strong>
              <p>some info about nodoes</p>
          </div>
      </div>
        </div>
  </div>
</div>

src/console/templates/console/tabs/utilities.html
<div class="tabs-container">
     <ul class="nav nav-tabs">
         <li class=""><a data-toggle="tab" href="#info" aria-expanded="true"> Information</a></li>
         <li class="active"><a data-toggle="tab" href="#Firmwares" aria-expanded="false">Firmwares</a></li>
         <li class=""><a data-toggle="tab" href="#servers" aria-expanded="false">External servers</a></li>
     </ul>
    <div class="tab-content">
        <div id="info" class="tab-pane">
                        <div class="panel-body">
                            <strong>gateway #1</strong>
                            <p>some info about gateways</p>
                        </div>
                    </div>
        <div id="Firmwares" class="tab-pane active">
                        <div class="panel-body">
                            <div class="row">

                                    <div class="col-md-8">
                                    <div class="ibox float-e-margins" style="margin-bottom: 1px;">
                                            <div class="ibox-content" style="background: transparent; padding-bottom: 1px;">
                                                    <form id="form_upload" action="/firmware/upload" method="POST" enctype="multipart/form-data">
                                                        <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                                                <div class="form-control" data-trigger="fileinput">
                                                                    <i class="fa fa-file fileinput-exists"></i> 
                                                                    <span class="fileinput-filename"></span></div>
                                                                <span class="input-group-addon btn btn-default btn-file">
                                                                <span class="fileinput-new">Select file</span>
                                                                <span class="fileinput-exists">Change</span>
                                                                <input type="file" name="document">
                                                                </span>
                                                                <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                                                <a href="#" id="upload_button" class="input-group-addon btn btn-default fileinput-exists">Upload</a>
                                                                <a href="#" style="display: none" id="delete_button" class="input-group-addon btn btn-danger">Delete</a>
                                                        </div>
                                                    </form>
                                            </div>
                                    </div>
                                    </div>
                            </div>

                            <!--div class="row">
                                <div class="col-md-4">
                                </div>
                            </div-->
                                <div class="row">
                                            <div class="ibox float-e-margins">
                                                <div class="ibox-content" style="background: transparent;">

                                                        <div id="jstree">
                                                            </div>
                                                </div>
                                        </div>
                                    </div>
                                
                        </div>
        </div>
        <div id="servers" class="tab-pane ">
          <div class="panel-body">
              <strong>node #1</strong>
              <p>some info about nodoes</p>
          </div>
      </div>
        </div>
  </div>
</div>